import { useState, useEffect, useRef } from "react";
import {
  CheckCircle2,
  XCircle,
  AlertCircle,
  Play,
  FileCode,
  BookOpen,
  Terminal,
  GraduationCap,
  Briefcase,
  Save,
  RefreshCw,
  FileText,
  ChevronRight,
  FolderOpen,
  ExternalLink,
  Award,
  RotateCcw,
  Info,
  Calendar,
  Code,
  Check,
  ChevronDown
} from "lucide-react";

// Definitions of the 9 required portfolio screenshots for easy browsing
const PORTFOLIO_ASSETS = [
  {
    id: "folder-structure",
    title: "1. Project Folder Structure",
    desc: "A neat view of the standard folder layout in an IDE, isolating business files in src/ from unit tests in tests/.",
    type: "tree"
  },
  {
    id: "app-home",
    title: "2. Application Homepage",
    desc: "The pristine UI of the Task Management Application, ready to capture and log task records.",
    type: "app-preview"
  },
  {
    id: "task-add",
    title: "3. Task Added Successfully",
    desc: "Demonstrates adding an active task, refreshing counts, sorting, and committing serialization blocks.",
    type: "task-added"
  },
  {
    id: "task-delete",
    title: "4. Task Deleted Successfully",
    desc: "Demonstrates removing an active task from the grid, triggering immutable state updates.",
    type: "task-deleted"
  },
  {
    id: "npm-test",
    title: "5. Terminal showing 'npm test'",
    desc: "How the terminal presents itself when the automated test runner is booted up in the local repository.",
    type: "npm-test-run"
  },
  {
    id: "all-passed",
    title: "6. Terminal showing 'All Tests Passed'",
    desc: "The green light: displaying successful assertions across all 4 files (Task Manager, Storage, Validation, Utils).",
    type: "all-passed-results"
  },
  {
    id: "coverage-report",
    title: "7. Istanbul Coverage Report (Terminal)",
    desc: "Shows high percentages of statement, branch, and function coverages generated by Jest's coverage tool.",
    type: "coverage-terminal"
  },
  {
    id: "coverage-summary",
    title: "8. Jest Coverage Directory",
    desc: "An overview of how files and percentages map out cleanly, validating comprehensive testing.",
    type: "coverage-dir"
  },
  {
    id: "github-repo",
    title: "9. GitHub Repository Submission",
    desc: "A simulated mock-up of how this project would look as a stellar, clean, open-source portfolio submission on GitHub.",
    type: "github-repo-mock"
  }
];

// Quiz data on Jest concepts
const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: "What is JSDOM in the context of Jest testing?",
    options: [
      "A database configuration for storing test data.",
      "An in-memory simulation of a browser environment running in Node.js.",
      "A compiler that translates ES6 JavaScript into standard CommonJS.",
      "A framework used to run end-to-end browser clicking tests."
    ],
    answer: 1,
    explanation: "JSDOM is an in-memory simulation of browser APIs (like window, document, and localStorage) running inside Node.js, allowing Jest to test frontend DOM-related functions without opening a real browser."
  },
  {
    id: 2,
    question: "Which Jest hook should you use to clear local storage before each individual test?",
    options: [
      "beforeAll()",
      "beforeEach()",
      "afterAll()",
      "afterEach()"
    ],
    answer: 1,
    explanation: "beforeEach() runs before every single test case, making it the ideal hook to reset database or localStorage mocks to guarantee complete isolation between tests."
  },
  {
    id: 3,
    question: "What is the difference between toBe() and toEqual() in Jest assertions?",
    options: [
      "toBe() is for arrays, while toEqual() is for numbers.",
      "toEqual() checks strict identity (Object.is), while toBe() parses deep object values.",
      "toBe() checks strict identity (Object.is) for primitive values, while toEqual() recursively checks deep equality of objects or arrays.",
      "There is no difference; they are exact aliases."
    ],
    answer: 2,
    explanation: "toBe() checks strict mathematical identity (Object.is), while toEqual() recursively traverses objects and arrays to verify deep structural equality."
  },
  {
    id: 4,
    question: "What is 'Branch Coverage' in a Jest code coverage report?",
    options: [
      "The percentage of Git branches that have been tested.",
      "The percentage of conditional paths (e.g., if/else blocks) that have been executed by tests.",
      "The amount of helper functions successfully imported.",
      "The total lines of code that contain comments."
    ],
    answer: 1,
    explanation: "Branch coverage verifies if the test suites have executed both paths (true and false) of every conditional statement, such as if/else blocks and logical operators."
  },
  {
    id: 5,
    question: "How do you assert that a function throws an error in Jest?",
    options: [
      "expect(myFunc).toThrow(errorMessage)",
      "expect(myFunc()).toThrow(errorMessage)",
      "expect(myFunc).toBeError()",
      "expect(myFunc).not.toBeValid()"
    ],
    answer: 0,
    explanation: "In Jest, to assert that an error is thrown, you must pass the function wrapper itself (without invoking it immediately, i.e., expect(myFunc)), so Jest can catch the error during its internal execution."
  }
];

export default function App() {
  // Navigation State
  const [activeTab, setActiveTab] = useState<"playground" | "code" | "education" | "quiz" | "portfolio">("playground");
  
  // File Explorer & Editor State
  const [files, setFiles] = useState<Record<string, string>>({});
  const [selectedFile, setSelectedFile] = useState<string>("src/taskManager.js");
  const [editorContent, setEditorContent] = useState<string>("");
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);

  // Jest Running State
  const [isRunningTests, setIsRunningTests] = useState<boolean>(false);
  const [testResults, setTestResults] = useState<any>(null);
  const [coverageSummary, setCoverageSummary] = useState<any>(null);
  const [rawStdout, setRawStdout] = useState<string>("");
  const [rawStderr, setRawStderr] = useState<string>("");
  const [testSuccess, setTestSuccess] = useState<boolean | null>(null);
  
  // Quiz State
  const [quizAnswers, setQuizAnswers] = useState<Record<number, number>>({});
  const [showQuizScore, setShowQuizScore] = useState<boolean>(false);
  const [quizSubmitted, setQuizSubmitted] = useState<boolean>(false);

  // Portfolio Sub-Asset Selector
  const [selectedAsset, setSelectedAsset] = useState<string>("folder-structure");

  // Iframe reload trigger
  const [iframeKey, setIframeKey] = useState<number>(0);

  // Load initial files and run a quick test sweep on mount
  useEffect(() => {
    fetchFiles();
    triggerTestRun(true); // Silent run on mount
  }, []);

  // Update editor when file selection changes
  useEffect(() => {
    if (files[selectedFile]) {
      setEditorContent(files[selectedFile]);
    }
  }, [selectedFile, files]);

  // Fetch file list and contents
  const fetchFiles = async () => {
    try {
      const res = await fetch("/api/files");
      if (res.ok) {
        const data = await res.json();
        setFiles(data.files);
        if (data.files[selectedFile]) {
          setEditorContent(data.files[selectedFile]);
        }
      }
    } catch (e) {
      console.error("Error fetching files:", e);
    }
  };

  // Run Jest tests on the server
  const triggerTestRun = async (silent = false) => {
    if (!silent) setIsRunningTests(true);
    try {
      const res = await fetch("/api/run-tests", { method: "POST" });
      if (res.ok) {
        const data = await res.json();
        setTestResults(data.testResults);
        setCoverageSummary(data.coverageSummary);
        setRawStdout(data.stdout);
        setRawStderr(data.stderr);
        setTestSuccess(data.success);
      }
    } catch (e) {
      console.error("Error executing Jest run:", e);
    } finally {
      if (!silent) setIsRunningTests(false);
    }
  };

  // Save changes to file and trigger hot reload
  const handleSaveFile = async () => {
    setIsSaving(true);
    setSaveStatus(null);
    try {
      const res = await fetch("/api/files", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filePath: selectedFile, content: editorContent })
      });
      if (res.ok) {
        setSaveStatus("success");
        // Update files state
        setFiles(prev => ({ ...prev, [selectedFile]: editorContent }));
        // Reload iframe to capture updated logic
        setIframeKey(k => k + 1);
        // Automatically run tests to see if code changes fixed or broke coverage
        await triggerTestRun(true);
        setTimeout(() => setSaveStatus(null), 3000);
      } else {
        setSaveStatus("error");
      }
    } catch (e) {
      setSaveStatus("error");
    } finally {
      setIsSaving(false);
    }
  };

  // Handle Quiz selection
  const handleQuizOptionSelect = (qId: number, oIdx: number) => {
    if (quizSubmitted) return;
    setQuizAnswers(prev => ({ ...prev, [qId]: oIdx }));
  };

  const handleQuizSubmit = () => {
    setQuizSubmitted(true);
    setShowQuizScore(true);
  };

  const resetQuiz = () => {
    setQuizAnswers({});
    setQuizSubmitted(false);
    setShowQuizScore(false);
  };

  // Fetch coverage metrics safely
  const getCoverageStat = (type: "statements" | "branches" | "functions" | "lines") => {
    if (!coverageSummary || !coverageSummary.total) return { pct: 0, covered: 0, total: 0 };
    return coverageSummary.total[type] || { pct: 0, covered: 0, total: 0 };
  };

  const stats = {
    statements: getCoverageStat("statements"),
    branches: getCoverageStat("branches"),
    functions: getCoverageStat("functions"),
    lines: getCoverageStat("lines")
  };

  // Help explanations mapped to each file in editor to assist learners
  const getFileExplanation = (fileName: string) => {
    switch (fileName) {
      case "src/taskManager.js":
        return "Contains the core functional modifiers: `addTask`, `editTask`, `deleteTask`, `completeTask`, `searchTask`, and `filterTasks`. Uses immutable patterns (returning new copies instead of direct mutation) which are optimal for predictable frontend state and standard unit testing.";
      case "src/validation.js":
        return "Our business validation rules module. It validates task title strings against character length ceilings (50 chars), checks for non-empty text, handles strict type audits, and performs a case-insensitive scan against existing records to avoid duplicates.";
      case "src/storage.js":
        return "Wraps browser `localStorage` dynamically. Incorporates defensive programming patterns (try/catch blocks) to safeguard state transfers and prevent application crashes if standard web storage fails, overflows, or is run outside the browser.";
      case "src/utils.js":
        return "Houses supporting utilities: a unique ID generator leveraging random seed fallbacks, a safe date formatter mapping objects to uniform YYYY-MM-DD values, and array sorters mapping lists alphabetically or chronologically.";
      case "tests/taskManager.test.js":
        return "Tests the complete task lifecycle. Demonstrates standard Jest assertions like `.toEqual()` to check deep object mutations, error assertion blocks (`toThrow()`) to block invalid submissions, and custom array filter checks.";
      case "tests/validation.test.js":
        return "Validates each input boundary case. Employs descriptive scenarios to confirm precise limits (e.g. testing string structures, checking character overflows, and ensuring self-records can preserve names during editing).";
      case "tests/storage.test.js":
        return "Demonstrates mockup strategies in Jest. Uses spies (`jest.spyOn`) to intercept browser storage calls and mock functions to simulate full write processes, reading corrupted JSON arrays, and handling quota exceptions.";
      case "tests/utils.test.js":
        return "Tests helpers with diverse inputs. Includes mocks to check global crypto engines, chronological date evaluations, and edge cases where missing values default to Epoch values.";
      case "jest.config.js":
        return "Configures the Jest test runner. It sets the execution environment to JSDOM (simulated browser), defines the coverage engine to map file lines, and targets the correct test directories.";
      case "babel.config.js":
        return "Tells Babel how to compile ES6 modules (import/export syntax) down to Node-compatible formats, allowing Jest to read production modules successfully without bundler builds.";
      default:
        return "This project configuration is fully editable! Modify the code blocks, save your edits, and watch Jest process and evaluate the results in real-time in the terminal.";
    }
  };

  // Counts of passed tests
  const totalSuites = testResults?.numTotalTestSuites || 0;
  const passedSuites = testResults?.numPassedTestSuites || 0;
  const totalTests = testResults?.numTotalTests || 0;
  const passedTests = testResults?.numPassedTests || 0;

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 flex flex-col font-sans selection:bg-purple-100 selection:text-purple-900">
      {/* 1. APP HEADER */}
      <header className="border-b border-slate-200 bg-white px-6 py-4 flex flex-col md:flex-row items-center justify-between gap-4 sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center text-white font-bold shadow-sm shadow-purple-200">
            <Terminal className="w-5 h-5 text-white stroke-[2.5]" />
          </div>
          <div>
            <h1 className="text-lg font-semibold text-slate-800 tracking-tight flex items-center gap-2">
              Frontend Testing
              <span className="text-slate-400 font-normal italic text-sm">// Task Manager Edition</span>
            </h1>
            <p className="text-xs text-slate-500 mt-0.5">
              Task Management App containing standard configurations, coverage graphs, and a live Jest runner.
            </p>
          </div>
        </div>

        {/* Quick run summary on header */}
        <div className="flex items-center gap-3">
          <div className="flex items-center space-x-2 bg-emerald-50 text-emerald-700 px-3 py-1.5 rounded-full border border-emerald-200 text-xs font-medium">
            <span className={`w-2 h-2 rounded-full ${testSuccess === true ? "bg-emerald-500 animate-pulse" : testSuccess === false ? "bg-rose-500" : "bg-amber-400"}`} />
            <span>Tests Passing: {testSuccess === true ? "100%" : testSuccess === false ? "Some Failing" : "Ready"}</span>
          </div>
          {testResults && (
            <div className="flex items-center space-x-2 bg-blue-50 text-blue-700 px-3 py-1.5 rounded-full border border-blue-200 text-xs font-medium">
              <span>Coverage: {stats.statements.pct}%</span>
            </div>
          )}
        </div>
      </header>

      {/* 2. TAB NAVIGATION */}
      <nav className="bg-white border-b border-slate-200 px-6 overflow-x-auto flex scrollbar-none">
        <div className="flex gap-1 py-2">
          <button
            onClick={() => setActiveTab("playground")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${
              activeTab === "playground"
                ? "bg-purple-50 text-purple-700 border border-purple-200"
                : "text-slate-600 hover:text-slate-900 hover:bg-slate-50"
            }`}
          >
            <Play className="w-4 h-4" />
            Playground & App
          </button>
          <button
            onClick={() => setActiveTab("code")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${
              activeTab === "code"
                ? "bg-purple-50 text-purple-700 border border-purple-200"
                : "text-slate-600 hover:text-slate-900 hover:bg-slate-50"
            }`}
          >
            <FileCode className="w-4 h-4" />
            Source Files & Editor
          </button>
          <button
            onClick={() => setActiveTab("education")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${
              activeTab === "education"
                ? "bg-purple-50 text-purple-700 border border-purple-200"
                : "text-slate-600 hover:text-slate-900 hover:bg-slate-50"
            }`}
          >
            <BookOpen className="w-4 h-4" />
            Educational Guide
          </button>
          <button
            onClick={() => setActiveTab("quiz")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${
              activeTab === "quiz"
                ? "bg-purple-50 text-purple-700 border border-purple-200"
                : "text-slate-600 hover:text-slate-900 hover:bg-slate-50"
            }`}
          >
            <GraduationCap className="w-4 h-4" />
            Concept Quiz
          </button>
          <button
            onClick={() => setActiveTab("portfolio")}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${
              activeTab === "portfolio"
                ? "bg-purple-50 text-purple-700 border border-purple-200"
                : "text-slate-600 hover:text-slate-900 hover:bg-slate-50"
            }`}
          >
            <Briefcase className="w-4 h-4" />
            Portfolio Screenshots
          </button>
        </div>
      </nav>

      {/* 3. MAIN DASHBOARD CONTENT */}
      <main className="flex-1 p-6 max-w-7xl w-full mx-auto flex flex-col gap-6">
        
        {/* TAB 1: PLAYGROUND & APP */}
        {activeTab === "playground" && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            
            {/* Live App Frame Container */}
            <div className="lg:col-span-7 flex flex-col gap-4">
              <div className="bg-white border border-slate-200 rounded-xl overflow-hidden flex flex-col h-[580px] shadow-sm">
                <div className="bg-slate-50 border-b border-slate-200 px-4 py-3 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-red-400" />
                    <span className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
                    <span className="w-2.5 h-2.5 rounded-full bg-green-400" />
                    <span className="text-xs text-slate-400 ml-2 font-mono">
                      https://localhost/app/index.html
                    </span>
                  </div>
                  <button 
                    onClick={() => setIframeKey(k => k + 1)} 
                    className="p-1 hover:bg-slate-800 rounded text-slate-400 hover:text-white transition"
                    title="Reload Application Frame"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                  </button>
                </div>
                
                {/* Embed the static application directly in an iframe! */}
                <iframe
                  key={iframeKey}
                  src="/app/index.html"
                  className="w-full flex-1 bg-[#f8fafc] border-none"
                  sandbox="allow-scripts allow-same-origin"
                />
              </div>

              {/* Guide banner on playground */}
              <div className="bg-purple-50 border border-purple-100 rounded-xl p-4 flex items-start gap-3">
                <Info className="w-5 h-5 text-purple-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-sm font-semibold text-purple-800">Test Integration Demonstration</h4>
                  <p className="text-xs text-slate-600 mt-1">
                    This Task Management board is fully linked to local storage and modular scripts. Go ahead, add, delete, or complete some tasks! Then try editing files in the <b>"Source Files & Editor"</b> tab, hit Save, and run tests on the right to see Jest validate your live implementation.
                  </p>
                </div>
              </div>
            </div>

            {/* Test Run Panel & Terminal */}
            <div className="lg:col-span-5 flex flex-col gap-6">
              
              {/* Giant Trigger Button */}
              <button
                onClick={() => triggerTestRun(false)}
                disabled={isRunningTests}
                className={`w-full py-4 px-6 rounded-xl font-semibold flex items-center justify-center gap-3 transition shadow-sm ${
                  isRunningTests
                    ? "bg-slate-100 text-slate-400 cursor-not-allowed border border-slate-200"
                    : "bg-purple-600 hover:bg-purple-500 text-white shadow-purple-100 active:scale-[0.98]"
                }`}
              >
                {isRunningTests ? (
                  <RefreshCw className="w-5 h-5 animate-spin" />
                ) : (
                  <Play className="w-5 h-5 fill-current" />
                )}
                {isRunningTests ? "Executing Jest Test Runner..." : "⚡ Execute Jest Unit Tests"}
              </button>

              {/* Istanbul Coverage Metrics Card */}
              {coverageSummary && (
                <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-4 flex items-center gap-2">
                    <Award className="w-4 h-4 text-purple-600" />
                    Code Coverage Metrics
                  </h3>
                  <div className="grid grid-cols-2 gap-4">
                    {/* Statements */}
                    <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                      <span className="text-xs text-slate-500 block font-medium">Statements</span>
                      <div className="flex items-baseline justify-between mt-1">
                        <span className={`text-xl font-mono font-bold ${stats.statements.pct >= 90 ? "text-emerald-600" : stats.statements.pct >= 75 ? "text-amber-600" : "text-rose-600"}`}>
                          {stats.statements.pct}%
                        </span>
                        <span className="text-[10px] text-slate-400 font-mono">
                          {stats.statements.covered}/{stats.statements.total}
                        </span>
                      </div>
                      <div className="w-full bg-slate-200 rounded-full h-1.5 mt-2 overflow-hidden">
                        <div
                           className={`h-1.5 rounded-full ${stats.statements.pct >= 90 ? "bg-emerald-500" : stats.statements.pct >= 75 ? "bg-amber-500" : "bg-rose-500"}`}
                          style={{ width: `${stats.statements.pct}%` }}
                        />
                      </div>
                    </div>

                    {/* Branches */}
                    <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                      <span className="text-xs text-slate-500 block font-medium">Branches</span>
                      <div className="flex items-baseline justify-between mt-1">
                        <span className={`text-xl font-mono font-bold ${stats.branches.pct >= 90 ? "text-emerald-600" : stats.branches.pct >= 75 ? "text-amber-600" : "text-rose-600"}`}>
                          {stats.branches.pct}%
                        </span>
                        <span className="text-[10px] text-slate-400 font-mono">
                          {stats.branches.covered}/{stats.branches.total}
                        </span>
                      </div>
                      <div className="w-full bg-slate-200 rounded-full h-1.5 mt-2 overflow-hidden">
                        <div
                           className={`h-1.5 rounded-full ${stats.branches.pct >= 90 ? "bg-emerald-500" : stats.branches.pct >= 75 ? "bg-amber-500" : "bg-rose-500"}`}
                          style={{ width: `${stats.branches.pct}%` }}
                        />
                      </div>
                    </div>

                    {/* Functions */}
                    <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                      <span className="text-xs text-slate-500 block font-medium">Functions</span>
                      <div className="flex items-baseline justify-between mt-1">
                        <span className={`text-xl font-mono font-bold ${stats.functions.pct >= 90 ? "text-emerald-600" : stats.functions.pct >= 75 ? "text-amber-600" : "text-rose-600"}`}>
                          {stats.functions.pct}%
                        </span>
                        <span className="text-[10px] text-slate-400 font-mono">
                          {stats.functions.covered}/{stats.functions.total}
                        </span>
                      </div>
                      <div className="w-full bg-slate-200 rounded-full h-1.5 mt-2 overflow-hidden">
                        <div
                           className={`h-1.5 rounded-full ${stats.functions.pct >= 90 ? "bg-emerald-500" : stats.functions.pct >= 75 ? "bg-amber-500" : "bg-rose-500"}`}
                          style={{ width: `${stats.functions.pct}%` }}
                        />
                      </div>
                    </div>

                    {/* Lines */}
                    <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                      <span className="text-xs text-slate-500 block font-medium">Lines</span>
                      <div className="flex items-baseline justify-between mt-1">
                        <span className={`text-xl font-mono font-bold ${stats.lines.pct >= 90 ? "text-emerald-600" : stats.lines.pct >= 75 ? "text-amber-600" : "text-rose-600"}`}>
                          {stats.lines.pct}%
                        </span>
                        <span className="text-[10px] text-slate-400 font-mono">
                          {stats.lines.covered}/{stats.lines.total}
                        </span>
                      </div>
                      <div className="w-full bg-slate-200 rounded-full h-1.5 mt-2 overflow-hidden">
                        <div
                           className={`h-1.5 rounded-full ${stats.lines.pct >= 90 ? "bg-emerald-500" : stats.lines.pct >= 75 ? "bg-amber-500" : "bg-rose-500"}`}
                          style={{ width: `${stats.lines.pct}%` }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Terminal Emulator (stdout output) */}
              <div className="bg-slate-950 border border-slate-800 rounded-xl flex-1 flex flex-col overflow-hidden min-h-[300px] shadow-sm">
                <div className="bg-slate-900 px-4 py-2 border-b border-slate-800 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Terminal className="w-3.5 h-3.5 text-slate-400" />
                    <span className="text-xs font-mono font-semibold text-slate-300">
                      Jest Test Terminal stdout
                    </span>
                  </div>
                  <span className="text-[10px] bg-slate-800 text-slate-400 font-mono px-2 py-0.5 rounded">
                    bash - node
                  </span>
                </div>
                
                <div className="p-4 font-mono text-xs overflow-y-auto flex-1 leading-relaxed text-slate-300 space-y-1 h-[250px] whitespace-pre-wrap selection:bg-slate-800 scrollbar-thin">
                  {rawStderr || rawStdout ? (
                    <>
                      {rawStderr && <div className="text-slate-400">{rawStderr}</div>}
                      {rawStdout && <div className="text-slate-300">{rawStdout}</div>}
                    </>
                  ) : (
                    <div className="text-slate-500 flex flex-col items-center justify-center h-full gap-2">
                      <Terminal className="w-8 h-8 text-slate-700 animate-pulse" />
                      <p className="text-center text-xs">Click the execute button above to trigger the Jest runner inside the container and view output logs here.</p>
                    </div>
                  )}
                </div>
              </div>

            </div>
          </div>
        )}

        {/* TAB 2: SOURCE FILES & EDITOR */}
        {activeTab === "code" && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
            
            {/* Left Column: Explorer File Tree */}
            <div className="lg:col-span-3 bg-white border border-slate-200 rounded-xl p-4 flex flex-col gap-3 shadow-sm">
              <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 flex items-center gap-2 pb-2 border-b border-slate-100">
                <FolderOpen className="w-3.5 h-3.5 text-purple-600" />
                frontend-testing/
              </h3>

              <div className="space-y-4">
                {/* Src Directory */}
                <div>
                  <div className="text-xs font-semibold text-slate-600 flex items-center gap-1.5 px-2 py-1">
                    <span className="text-purple-500 font-bold">📁</span> src/
                  </div>
                  <div className="ml-4 space-y-0.5 border-l border-slate-200 pl-2 mt-1">
                    {["src/index.html", "src/style.css", "src/app.js", "src/taskManager.js", "src/storage.js", "src/validation.js", "src/utils.js"].map(filePath => (
                      <button
                        key={filePath}
                        onClick={() => setSelectedFile(filePath)}
                        className={`w-full text-left text-xs font-mono px-2 py-1.5 rounded transition flex items-center justify-between ${
                          selectedFile === filePath
                            ? "bg-purple-50 text-purple-700 font-bold"
                            : "text-slate-600 hover:bg-slate-50 hover:text-slate-900"
                        }`}
                      >
                        <span className="truncate">{filePath.replace("src/", "")}</span>
                        {filePath.endsWith(".js") && <span className="text-[10px] text-amber-600">JS</span>}
                        {filePath.endsWith(".html") && <span className="text-[10px] text-orange-600">HTML</span>}
                        {filePath.endsWith(".css") && <span className="text-[10px] text-indigo-500">CSS</span>}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Tests Directory */}
                <div>
                  <div className="text-xs font-semibold text-slate-600 flex items-center gap-1.5 px-2 py-1">
                    <span className="text-purple-500 font-bold">📁</span> tests/
                  </div>
                  <div className="ml-4 space-y-0.5 border-l border-slate-200 pl-2 mt-1">
                    {["tests/taskManager.test.js", "tests/validation.test.js", "tests/storage.test.js", "tests/utils.test.js"].map(filePath => (
                      <button
                        key={filePath}
                        onClick={() => setSelectedFile(filePath)}
                        className={`w-full text-left text-xs font-mono px-2 py-1.5 rounded transition flex items-center justify-between ${
                          selectedFile === filePath
                            ? "bg-purple-50 text-purple-700 font-bold"
                            : "text-slate-600 hover:bg-slate-50 hover:text-slate-900"
                        }`}
                      >
                        <span className="truncate">{filePath.replace("tests/", "")}</span>
                        <span className="text-[9px] bg-purple-100 text-purple-700 px-1 rounded font-semibold">TEST</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Configurations */}
                <div>
                  <div className="text-xs font-semibold text-slate-600 flex items-center gap-1.5 px-2 py-1">
                    <span className="text-slate-400">⚙️</span> Config Files
                  </div>
                  <div className="ml-4 space-y-0.5 border-l border-slate-200 pl-2 mt-1">
                    {["package.json", "jest.config.js", "babel.config.js", ".gitignore", "README.md"].map(filePath => (
                      <button
                        key={filePath}
                        onClick={() => setSelectedFile(filePath)}
                        className={`w-full text-left text-xs font-mono px-2 py-1.5 rounded transition flex items-center justify-between ${
                          selectedFile === filePath
                            ? "bg-purple-50 text-purple-700 font-bold"
                            : "text-slate-600 hover:bg-slate-50 hover:text-slate-900"
                        }`}
                      >
                        <span className="truncate">{filePath}</span>
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column: Code Editor & Explanations */}
            <div className="lg:col-span-9 flex flex-col gap-6">
              <div className="bg-white border border-slate-200 rounded-xl overflow-hidden flex flex-col shadow-sm">
                
                {/* Editor Header */}
                <div className="bg-slate-50 px-4 py-3 border-b border-slate-200 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Code className="w-4 h-4 text-purple-600" />
                    <span className="text-xs font-mono font-semibold text-slate-700">
                      frontend-testing/{selectedFile}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    {saveStatus === "success" && (
                      <span className="text-xs text-emerald-700 flex items-center gap-1 bg-emerald-50 border border-emerald-200 px-2 py-1 rounded">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> File Saved & Tests Updated!
                      </span>
                    )}
                    {saveStatus === "error" && (
                      <span className="text-xs text-rose-700 flex items-center gap-1 bg-rose-50 border border-rose-200 px-2 py-1 rounded">
                        <XCircle className="w-3.5 h-3.5 text-rose-600" /> Save failed!
                      </span>
                    )}

                    <button
                      onClick={handleSaveFile}
                      disabled={isSaving}
                      className="bg-purple-600 hover:bg-purple-500 text-white font-semibold px-3 py-1.5 rounded-lg text-xs flex items-center gap-1.5 transition"
                    >
                      {isSaving ? (
                        <RefreshCw className="w-3 h-3 animate-spin" />
                      ) : (
                        <Save className="w-3 h-3" />
                      )}
                      {isSaving ? "Saving..." : "Save File"}
                    </button>
                  </div>
                </div>

                {/* Code Editor Body */}
                <textarea
                  value={editorContent}
                  onChange={(e) => setEditorContent(e.target.value)}
                  className="w-full h-[450px] p-5 bg-slate-950 font-mono text-xs leading-relaxed text-slate-300 outline-none border-none resize-none selection:bg-slate-800"
                  spellCheck="false"
                />
              </div>

              {/* Explanations Area */}
              <div className="bg-white border border-slate-200 rounded-xl p-5 flex items-start gap-4 shadow-sm">
                <div className="bg-purple-50 p-2 rounded-lg border border-purple-100 text-purple-600">
                  <GraduationCap className="w-6 h-6 stroke-[1.8]" />
                </div>
                <div>
                  <h4 className="font-semibold text-slate-800 text-sm">Educational File Context</h4>
                  <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                    {getFileExplanation(selectedFile)}
                  </p>
                </div>
              </div>
            </div>

          </div>
        )}

        {/* TAB 3: EDUCATIONAL GUIDE */}
        {activeTab === "education" && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            
            {/* Card 1: What is Unit Testing */}
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-3">
              <span className="text-2xl">🧪</span>
              <h3 className="font-semibold text-slate-800 text-base">What is Unit Testing?</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Unit testing targets individual blocks (like functions or classes) in strict isolation. We bypass DOM operations or network APIs, passing precise inputs directly to functions and measuring their exact output.
              </p>
              <div className="bg-slate-950 rounded p-3 border border-slate-800/60 font-mono text-[10px] text-slate-300 mt-2">
                {`// Example Unit Testing:
const result = validateTask("");
expect(result.isValid).toBe(false);`}
              </div>
            </div>

            {/* Card 2: Why Jest */}
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-3">
              <span className="text-2xl">🃏</span>
              <h3 className="font-semibold text-slate-800 text-base">Why use Jest?</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Jest is a high-speed, zero-config testing engine developed by Meta. It includes a built-in virtual browser engine called <b>JSDOM</b>, which replicates DOM behaviors, web storage, and event models right inside Node.js!
              </p>
              <div className="bg-slate-950 rounded p-3 border border-slate-800/60 font-mono text-[10px] text-slate-300 mt-2">
                {`// JSDOM supports mock DOM:
document.body.innerHTML = "<ul></ul>";
expect(document.querySelector("ul")).toBeDefined();`}
              </div>
            </div>

            {/* Card 3: Test Lifecycle */}
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-3">
              <span className="text-2xl">⏳</span>
              <h3 className="font-semibold text-slate-800 text-base">Test Lifecycle Hooks</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Jest provides lifecycle hooks to cleanly manage scope states. Ensure perfect isolation between tests by invoking <code>beforeEach()</code> and <code>afterEach()</code> blocks to clean local storage or reset variable values.
              </p>
              <div className="bg-slate-950 rounded p-3 border border-slate-800/60 font-mono text-[10px] text-slate-300 mt-2">
                {`beforeEach(() => {
  localStorage.clear();
  jest.clearAllMocks();
});`}
              </div>
            </div>

            {/* Card 4: Assertions */}
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-3">
              <span className="text-2xl">🎯</span>
              <h3 className="font-semibold text-slate-800 text-base">Match & Assert</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Verify outputs using matchers. <code>toBe()</code> measures strict identity (Object.is) for strings or numbers. <code>toEqual()</code> recursively inspects objects and arrays, verifying deep structural matching.
              </p>
              <div className="bg-slate-950 rounded p-3 border border-slate-800/60 font-mono text-[10px] text-slate-300 mt-2">
                {`// toBe vs toEqual
expect(1 + 1).toBe(2);
expect({id: 1}).toEqual({id: 1});`}
              </div>
            </div>

            {/* Card 5: Mocking */}
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-3">
              <span className="text-2xl">🕵️</span>
              <h3 className="font-semibold text-slate-800 text-base">Mocking & Spies</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Replace browser integrations (like network fetch, crypto functions, or local storage items) with spies. This monitors invocation counts, captures passed inputs, and intercepts write errors without bricking.
              </p>
              <div className="bg-slate-950 rounded p-3 border border-slate-800/60 font-mono text-[10px] text-slate-300 mt-2">
                {`const spy = jest.spyOn(Storage.prototype, "setItem");
saveToLocalStorage([]);
expect(spy).toHaveBeenCalled();`}
              </div>
            </div>

            {/* Card 6: Best Practices */}
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-3">
              <span className="text-2xl">🌟</span>
              <h3 className="font-semibold text-slate-800 text-base">Best Practices</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Design pure state functions isolated from direct DOM dependencies. Always test edge cases (empty states, duplicate boundaries, long characters), clean mocks, and strive for 85%+ branch coverage!
              </p>
              <div className="bg-slate-950 rounded p-3 border border-slate-800/60 font-mono text-[10px] text-slate-300 mt-2">
                {`// Keep tests deterministic!
// Avoid nested conditions
// One assertion topic per test`}
              </div>
            </div>

          </div>
        )}

        {/* TAB 4: CONCEPT QUIZ */}
        {activeTab === "quiz" && (
          <div className="max-w-2xl mx-auto w-full bg-white border border-slate-200 rounded-2xl p-6 md:p-8 shadow-sm flex flex-col gap-6">
            
            <div className="text-center flex flex-col items-center gap-2 pb-4 border-b border-slate-100">
              <div className="text-amber-500 text-3xl">🏆</div>
              <h2 className="text-lg font-semibold text-slate-850">Automated Testing Knowledge Check</h2>
              <p className="text-xs text-slate-500">
                Evaluate your knowledge on Jest testing, JSDOM environments, assertions, and mock structures.
              </p>
            </div>

            <div className="space-y-6">
              {QUIZ_QUESTIONS.map((q, idx) => {
                const selectedOptionIdx = quizAnswers[q.id];
                const isCorrect = selectedOptionIdx === q.answer;

                return (
                  <div key={q.id} className="bg-slate-50 p-5 rounded-xl border border-slate-200 flex flex-col gap-3">
                    <span className="text-xs text-purple-600 font-bold uppercase tracking-wider font-mono">
                      Question {idx + 1} of {QUIZ_QUESTIONS.length}
                    </span>
                    <h4 className="font-medium text-sm text-slate-800 leading-relaxed">{q.question}</h4>
                    
                    <div className="flex flex-col gap-2 mt-2">
                      {q.options.map((opt, oIdx) => {
                        let btnStyle = "border-slate-200 bg-white text-slate-700 hover:border-slate-300";
                        
                        if (quizSubmitted) {
                          if (oIdx === q.answer) {
                            btnStyle = "border-emerald-200 bg-emerald-50 text-emerald-800 font-medium";
                          } else if (selectedOptionIdx === oIdx && !isCorrect) {
                            btnStyle = "border-rose-200 bg-rose-50 text-rose-800";
                          } else {
                            btnStyle = "border-slate-100 bg-white text-slate-400 opacity-60";
                          }
                        } else if (selectedOptionIdx === oIdx) {
                          btnStyle = "border-purple-500 bg-purple-50 text-purple-700 font-semibold";
                        }

                        return (
                          <button
                            key={oIdx}
                            disabled={quizSubmitted}
                            onClick={() => handleQuizOptionSelect(q.id, oIdx)}
                            className={`w-full text-left text-xs p-3.5 rounded-lg border transition flex items-center justify-between ${btnStyle}`}
                          >
                            <span>{opt}</span>
                            {!quizSubmitted && selectedOptionIdx === oIdx && (
                              <span className="w-2 h-2 rounded-full bg-purple-500" />
                            )}
                            {quizSubmitted && oIdx === q.answer && (
                              <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 ml-2" />
                            )}
                            {quizSubmitted && selectedOptionIdx === oIdx && !isCorrect && (
                              <XCircle className="w-4 h-4 text-rose-600 flex-shrink-0 ml-2" />
                            )}
                          </button>
                        );
                      })}
                    </div>

                    {quizSubmitted && (
                      <div className="mt-3 text-xs bg-white p-3 rounded border border-slate-200 text-slate-500 leading-relaxed">
                        <span className="font-bold text-slate-700">Explanation:</span> {q.explanation}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Submit / Reset Actions */}
            <div className="flex flex-col items-center gap-4 mt-4 pt-4 border-t border-slate-100">
              {showQuizScore ? (
                <div className="text-center flex flex-col items-center gap-2">
                  <div className="text-xl font-bold text-slate-800 font-mono">
                    Score:{" "}
                    <span className="text-purple-600">
                      {QUIZ_QUESTIONS.filter(q => quizAnswers[q.id] === q.answer).length}
                    </span>{" "}
                    / {QUIZ_QUESTIONS.length}
                  </div>
                  <p className="text-xs text-slate-500">
                    {QUIZ_QUESTIONS.filter(q => quizAnswers[q.id] === q.answer).length === QUIZ_QUESTIONS.length
                      ? "Outstanding! You scored a perfect score. You are ready for automated testing!"
                      : "Great job! Review the explanations above to solidify your Jest unit testing concepts."}
                  </p>
                  <button
                    onClick={resetQuiz}
                    className="mt-2 text-xs text-purple-600 flex items-center gap-1.5 border border-purple-200 bg-purple-50 px-4 py-2 rounded-lg hover:bg-purple-100 transition"
                  >
                    <RotateCcw className="w-3.5 h-3.5" /> Reset Quiz
                  </button>
                </div>
              ) : (
                <button
                  onClick={handleQuizSubmit}
                  disabled={Object.keys(quizAnswers).length < QUIZ_QUESTIONS.length}
                  className={`w-full py-3.5 px-6 rounded-xl font-semibold transition ${
                    Object.keys(quizAnswers).length < QUIZ_QUESTIONS.length
                      ? "bg-slate-100 text-slate-400 cursor-not-allowed border border-slate-200"
                      : "bg-purple-600 hover:bg-purple-500 text-white shadow-sm"
                  }`}
                >
                  Submit Answers
                </button>
              )}
            </div>

          </div>
        )}

        {/* TAB 5: PORTFOLIO SCREENSHOTS */}
        {activeTab === "portfolio" && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            
            {/* Sidebar selectors */}
            <div className="lg:col-span-4 bg-white border border-slate-200 rounded-xl p-4 flex flex-col gap-2 shadow-sm">
              <div className="pb-3 mb-2 border-b border-slate-100">
                <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2">
                  <Briefcase className="w-4 h-4 text-purple-600" />
                  Internship Assets Map
                </h3>
                <p className="text-[11px] text-slate-500 mt-1">
                  Required screenshots for your GitHub README and portfolio submission. Browse simulations of them below.
                </p>
              </div>

              <div className="space-y-1">
                {PORTFOLIO_ASSETS.map(asset => (
                  <button
                    key={asset.id}
                    onClick={() => setSelectedAsset(asset.id)}
                    className={`w-full text-left text-xs p-3 rounded-lg border transition flex items-center justify-between ${
                      selectedAsset === asset.id
                        ? "bg-purple-50 border-purple-200 text-purple-700 font-semibold"
                        : "border-transparent bg-transparent text-slate-500 hover:bg-slate-50 hover:text-slate-800"
                    }`}
                  >
                    <span className="truncate">{asset.title}</span>
                    <ChevronRight className="w-3.5 h-3.5 opacity-60" />
                  </button>
                ))}
              </div>
            </div>

            {/* Asset High Fidelity Simulation */}
            <div className="lg:col-span-8 flex flex-col gap-4">
              <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm flex flex-col gap-2">
                <h3 className="font-semibold text-slate-800 text-base">
                  {PORTFOLIO_ASSETS.find(a => a.id === selectedAsset)?.title}
                </h3>
                <p className="text-xs text-slate-600 leading-relaxed">
                  {PORTFOLIO_ASSETS.find(a => a.id === selectedAsset)?.desc}
                </p>
              </div>

              {/* High-fidelity simulation box */}
              <div className="bg-slate-950 border border-slate-800 rounded-xl overflow-hidden min-h-[420px] shadow-sm flex flex-col">
                <div className="bg-slate-900 px-4 py-2.5 border-b border-slate-800 flex items-center justify-between text-slate-400 text-[11px]">
                  <span className="font-mono">Pristine Simulated Asset - Preview</span>
                  <span className="bg-slate-800 px-2 py-0.5 rounded font-mono text-[9px]">
                    100% Scale Vector Mock
                  </span>
                </div>

                <div className="p-6 flex-1 flex flex-col items-center justify-center font-mono">
                  
                  {/* SIMULATED VIEW 1: FOLDER TREE */}
                  {selectedAsset === "folder-structure" && (
                    <div className="text-xs w-full max-w-sm border border-slate-800 bg-[#0c101b] p-5 rounded-lg space-y-1.5 shadow-md text-slate-300">
                      <div>📁 frontend-testing</div>
                      <div className="pl-4 border-l border-slate-800/80 ml-2">
                        <div>📁 coverage</div>
                        <div>📁 src</div>
                        <div className="pl-4 border-l border-slate-800/80 ml-2 text-slate-400">
                          <div>📄 app.js</div>
                          <div>📄 index.html</div>
                          <div>📄 storage.js</div>
                          <div>📄 style.css</div>
                          <div>📄 taskManager.js</div>
                          <div>📄 utils.js</div>
                          <div>📄 validation.js</div>
                        </div>
                        <div>📁 tests</div>
                        <div className="pl-4 border-l border-slate-800/80 ml-2 text-slate-400">
                          <div>📄 storage.test.js</div>
                          <div>📄 taskManager.test.js</div>
                          <div>📄 utils.test.js</div>
                          <div>📄 validation.test.js</div>
                        </div>
                        <div className="text-slate-400">📄 .gitignore</div>
                        <div className="text-slate-400">📄 babel.config.js</div>
                        <div className="text-slate-400">📄 jest.config.js</div>
                        <div className="text-slate-400">📄 package.json</div>
                        <div className="text-slate-400">📄 README.md</div>
                      </div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 2: HOMEPAGE PREVIEW */}
                  {selectedAsset === "app-home" && (
                    <div className="border border-slate-200 bg-white text-slate-900 rounded-lg shadow-md w-full max-w-md overflow-hidden flex flex-col text-xs font-sans">
                      <div className="bg-slate-50 px-4 py-2 border-b flex items-center justify-between text-[10px] text-slate-500 font-mono">
                        <span>Task Manager (Testing Edition)</span>
                        <span>v1.0.0</span>
                      </div>
                      <div className="p-4 space-y-4">
                        <div className="text-center py-2 border-b border-slate-100">
                          <h4 className="font-semibold text-slate-800 text-sm">Task Manager</h4>
                          <p className="text-[10px] text-slate-400 mt-0.5">Tested using Jest, stored in LocalStorage</p>
                        </div>
                        <div className="bg-slate-50 p-3 rounded border border-slate-200">
                          <h5 className="font-semibold text-slate-750 mb-1.5">Create New Task</h5>
                          <div className="h-6 bg-white border border-slate-200 rounded px-2 flex items-center text-slate-400 mb-1.5 text-[10px]">
                            e.g. Write integration tests
                          </div>
                          <div className="h-7 bg-purple-600 text-white font-semibold rounded flex items-center justify-center cursor-pointer text-[10px]">
                            Add Task
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 3: TASK ADDED */}
                  {selectedAsset === "task-add" && (
                    <div className="border border-slate-200 bg-white text-slate-900 rounded-lg shadow-md w-full max-w-md overflow-hidden flex flex-col text-xs font-sans">
                      <div className="bg-slate-50 px-4 py-2 border-b flex items-center justify-between text-[10px] text-slate-500 font-mono">
                        <span>Success Action Simulation</span>
                        <span className="text-emerald-600 font-semibold">1 Active Record</span>
                      </div>
                      <div className="p-4 space-y-3">
                        <div className="bg-emerald-50 border border-emerald-100 text-emerald-800 p-2 rounded text-[10px] flex items-center gap-1.5">
                          ✓ Task "Write automated unit tests" created successfully!
                        </div>
                        <div className="border border-slate-200 p-3 rounded flex items-center justify-between bg-white shadow-sm">
                          <div className="flex items-center gap-2">
                            <span className="w-4 h-4 rounded border border-slate-300 bg-white" />
                            <div>
                              <p className="font-semibold text-slate-800 text-[11px]">Write automated unit tests</p>
                              <span className="bg-slate-100 text-slate-500 text-[9px] px-1.5 py-0.5 rounded font-mono">Work</span>
                            </div>
                          </div>
                          <span className="text-slate-400 font-mono">🗑️</span>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 4: TASK DELETED */}
                  {selectedAsset === "task-deleted" && (
                    <div className="border border-slate-200 bg-white text-slate-900 rounded-lg shadow-md w-full max-w-md overflow-hidden flex flex-col text-xs font-sans">
                      <div className="bg-slate-50 px-4 py-2 border-b flex items-center justify-between text-[10px] text-slate-500 font-mono">
                        <span>Task deleted simulation</span>
                        <span className="text-slate-500">0 Active Records</span>
                      </div>
                      <div className="p-6 text-center text-slate-500 space-y-2 flex flex-col items-center">
                        <div className="text-slate-300 text-2xl">✓</div>
                        <h5 className="font-semibold text-slate-750">No tasks found</h5>
                        <p className="text-[10px] text-slate-400">Get started by adding a task or adjusting your filters.</p>
                      </div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 5: npm test run */}
                  {selectedAsset === "npm-test" && (
                    <div className="text-xs w-full max-w-md border border-slate-800 bg-[#0c101b] p-5 rounded-lg space-y-2 shadow-md text-slate-300 leading-relaxed">
                      <div className="text-slate-500 font-mono">$ npm test</div>
                      <div className="text-slate-400 mt-2">
                        {`> jest --passWithNoTests`}
                      </div>
                      <div className="text-purple-400 mt-1 font-semibold animate-pulse">
                        {`RUNS  tests/taskManager.test.js`}
                      </div>
                      <div className="text-purple-400 font-semibold animate-pulse">
                        {`RUNS  tests/validation.test.js`}
                      </div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 6: ALL PASSED */}
                  {selectedAsset === "all-passed" && (
                    <div className="text-xs w-full max-w-lg border border-slate-800 bg-[#050811] p-5 rounded-lg space-y-1 text-slate-300 shadow-md leading-relaxed">
                      <div><span className="bg-emerald-500 text-slate-950 px-1 rounded font-bold mr-2 text-[10px]">PASS</span> tests/taskManager.test.js</div>
                      <div><span className="bg-emerald-500 text-slate-950 px-1 rounded font-bold mr-2 text-[10px]">PASS</span> tests/validation.test.js</div>
                      <div><span className="bg-emerald-500 text-slate-950 px-1 rounded font-bold mr-2 text-[10px]">PASS</span> tests/storage.test.js</div>
                      <div><span className="bg-emerald-500 text-slate-950 px-1 rounded font-bold mr-2 text-[10px]">PASS</span> tests/utils.test.js</div>
                      <div className="text-slate-500 pt-3">-----------------------------------------------------</div>
                      <div className="text-emerald-400 font-bold pt-1">Test Suites: 4 passed, 4 total</div>
                      <div className="text-emerald-400 font-bold">Tests:       26 passed, 26 total</div>
                      <div className="text-slate-400 font-medium">Snapshots:   0 total</div>
                      <div className="text-slate-400 font-medium">Time:        1.45 s, estimated 2 s</div>
                      <div className="text-slate-500 pt-1">Ran all test suites.</div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 7: COVERAGE TERMINAL */}
                  {selectedAsset === "coverage-report" && (
                    <div className="text-[10px] w-full max-w-xl border border-slate-800 bg-[#050811] p-4 rounded-lg text-slate-300 font-mono leading-tight shadow-md">
                      <div className="text-slate-400 mb-2">----------|---------|----------|---------|---------|-------------------</div>
                      <div className="font-bold text-white">File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s </div>
                      <div className="text-slate-400">----------|---------|----------|---------|---------|-------------------</div>
                      <div className="text-emerald-400 font-bold">All files |   96.15 |    93.75 |   95.45 |   95.91 |                   </div>
                      <div className="text-emerald-400"> storage.js|   91.66 |    90.00 |  100.00 |   90.90 | 25                </div>
                      <div className="text-emerald-400"> taskM... |  100.00 |   100.00 |  100.00 |  100.00 |                   </div>
                      <div className="text-emerald-400"> utils.js  |   94.11 |    85.71 |   80.00 |   93.33 | 31                </div>
                      <div className="text-emerald-400"> valid... |  100.00 |   100.00 |  100.00 |  100.00 |                   </div>
                      <div className="text-slate-400">----------|---------|----------|---------|---------|-------------------</div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 8: COVERAGE SUMMARY */}
                  {selectedAsset === "coverage-dir" && (
                    <div className="text-xs w-full max-w-sm border border-slate-800 bg-[#0c101b] p-5 rounded-lg space-y-2 shadow-md text-slate-300">
                      <div className="text-xs font-semibold text-slate-400 flex items-center gap-1.5 pb-2 border-b border-slate-800">
                        <span>📁</span> coverage/
                      </div>
                      <div className="pl-4 space-y-1 border-l border-slate-800 ml-2">
                        <div>📁 lcov-report</div>
                        <div className="pl-4 border-l border-slate-800 ml-2 text-slate-500">
                          <div>📄 index.html <span className="text-[10px] text-purple-400">(View Report in Browser)</span></div>
                          <div>📄 base.css</div>
                          <div>📄 prettify.js</div>
                        </div>
                        <div>📄 clover.xml</div>
                        <div className="text-purple-400">📄 coverage-summary.json</div>
                        <div>📄 lcov.info</div>
                      </div>
                    </div>
                  )}

                  {/* SIMULATED VIEW 9: GITHUB REPO */}
                  {selectedAsset === "github-repo" && (
                    <div className="border border-slate-800 bg-[#0c101b] rounded-lg shadow-md w-full max-w-md overflow-hidden flex flex-col text-[11px] font-sans text-slate-300">
                      <div className="bg-slate-900 px-4 py-2 border-b border-slate-800 flex items-center justify-between text-slate-400 font-semibold font-mono">
                        <span>GitHub Simulator</span>
                        <span>https://github.com/intern/frontend-testing</span>
                      </div>
                      <div className="p-4 space-y-3">
                        <div className="flex items-center gap-1.5 text-xs text-white font-bold">
                          <span>📦</span> <span>internship-frontend-testing-jest</span>
                          <span className="text-[9px] bg-slate-850 text-slate-400 px-1.5 py-0.2 rounded">Public</span>
                        </div>
                        <div className="text-slate-400 border-b border-slate-800 pb-2">
                          A beginner-to-intermediate modular JavaScript Task Management Application demonstrating rigorous unit testing using Jest and web mocks.
                        </div>
                        <div className="space-y-1 pt-1">
                          <div className="flex items-center justify-between bg-slate-900 p-2 rounded">
                            <span className="font-mono text-purple-400">tests/</span>
                            <span className="text-slate-500 text-[10px]">Add coverage files and spy tests</span>
                          </div>
                          <div className="flex items-center justify-between bg-slate-900 p-2 rounded">
                            <span className="font-mono text-purple-400">src/</span>
                            <span className="text-slate-500 text-[10px]">Implement functional logic</span>
                          </div>
                          <div className="flex items-center justify-between bg-slate-900 p-2 rounded">
                            <span className="font-mono text-slate-300">jest.config.js</span>
                            <span className="text-slate-500 text-[10px]">Setup JSDOM sandbox</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                </div>
              </div>

              {/* Instructions banner on how to save screenshots */}
              <div className="bg-white border border-slate-200 rounded-xl p-5 flex items-start gap-4 shadow-sm">
                <div className="bg-purple-50 p-2 rounded-lg border border-purple-100 text-purple-600">
                  <Briefcase className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-slate-850 text-sm">Portfolio Capturing Instruction</h4>
                  <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                    To capture real terminal screenshots for your internship or GitHub project page, open a shell in your local system, navigate inside <code>frontend-testing</code>, run <code>npm test</code> or <code>npm run coverage</code>, and take a screenshot of your actual system terminal! You can also use the live vector maps displayed here as layout ideas.
                  </p>
                </div>
              </div>

            </div>
          </div>
        )}

      </main>

      {/* 4. FOOTER */}
      <footer className="border-t border-slate-200 bg-white py-5 text-center px-6">
        <p className="text-xs text-slate-500 font-mono">
          © 2026 Jest Testing Playground. Created for educational purposes & Internship Showcase portfolios.
        </p>
      </footer>
    </div>
  );
}
